name: Deploy kallakuri Admin App (main)
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Create an archive of the repo at HEAD (no .git / node_modules)
      - name: Package code
        run: |
          git archive --format=tar.gz -o deploy.tgz HEAD
          ls -lh deploy.tgz

      - name: Upload code to server (scp)
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy.tgz"
          target: "/tmp/kallakuri-admin_deploy/"

      - name: Install, restart with PM2, reload Nginx (ssh)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_SSH_HOST }}
          username: ${{ secrets.SSH_USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -euo pipefail

            APP_DIR="/home/helloandhellomrk-admin/htdocs/admin.helloandhellomrk.in"
            TMP_DIR="/tmp/kallakuri-admin_deploy"

            sudo mkdir -p "$APP_DIR" "$TMP_DIR"
            sudo chown -R "$USER":"$USER" "$APP_DIR" "$TMP_DIR"

            # Unpack the new code into the app directory
            tar -xzf "$TMP_DIR/deploy.tgz" -C "$APP_DIR"

            cd "$APP_DIR"

            # (Optional) ensure correct Node version if you use nvm
            if command -v nvm >/dev/null 2>&1; then
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
              nvm install --lts >/dev/null 2>&1 || true
              nvm use --lts
              hash -r
            fi

            node -v
            npm -v

            # Install deps
            npm install --no-audit --no-fund
            npm run build

            # PM2: restart if exists; otherwise start with PORT=3001
            if pm2 describe realstate-node-app >/dev/null 2>&1; then
              pm2 restart kallakuri-admin-app
            else
              PORT=3001 pm2 start npm --name "kallakuri-admin-app" -- start
            fi

            pm2 save

            # Reload/restart nginx (choose one)
            sudo systemctl reload nginx || sudo systemctl restart nginx



          
